import pytest

from phys305_hw3 import prior0_n0, prior0_lmbda


def test_prior0_n0():
    """Test the uniform prior for n0 generated by prior0_n0().

    For n=4, we expect the n0 grid to be [0, 100, 200, 300] and the
    normalized uniform prior to be constant, with each value equal to
    1/300.

    """
    n0s, ps_n0 = prior0_n0(l=0, u=300, n=4)

    assert n0s   == pytest.approx([0, 100, 200, 300])
    assert ps_n0 == pytest.approx(1/300)


def test_prior0_lmbda():
    """Test the log-normal prior for lmbda generated by
    prior0_lmbda().

    For n=5, we expect the lmbda grid to be logarithmically spaced
    between 1e-4 and 1, i.e., [1e-4, 1e-3, 1e-2, 1e-1, 1]. The prior
    probabilities are also compared against pre-computed expected
    values.

    """
    lmbdas, ps_lmbda = prior0_lmbda(l=1e-4, u=1, n=5, mu=np.log(0.01), sigma=np.log(2))

    assert lmbdas   == pytest.approx([1e-4, 1e-3, 1e-2, 1e-1, 1])
    assert ps_lmbda == pytest.approx([
        5.0474369195669805e-09,
        7.795871698888053e-02,
        1.941463711450083e+01,
        7.795871698888053e-02,
        5.0474369195669805e-09,
    ])
